### ISSUE TITLE
Adjusting the top-nav

### ISSUE THREAD

**Issue by MarcoMorawec** [benzegreatest/MyNewCoolRepository#2]
The nop-nav looks like it's not properly styled. 

Unless, you wanted to have the "contribute" and "about" links to be like this, take a look at the wireframes and adjust your css styles accordingly.

Here's what I'm seeing:

![screen shot 2015-07-03 at 7 56 09 am](https://cloud.githubusercontent.com/assets/1474717/8498809/5a746e2a-2159-11e5-96e7-f074af641edf.png)

**Comment by benzegreatest** [comment]
Hi Marco,
Sorry about that. Yes, I changed this part to look like that. I can change it back, not a problem.
Ben

**Comment by MarcoMorawec** [comment]
No problem at all. Feel free to leave it as is. I just wanted to make sure
that was on purpose.

Keep up the good work and make sure to close the issue :)

On Friday, July 3, 2015, benzegreatest notifications@github.com wrote:

> Hi Marco,
> Sorry about that. Yes, I changed this part to look like that. I can change
> it back, not a problem.
> Ben
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/benzegreatest/MyNewCoolRepository/issues/2#issuecomment-118394261
> .

## 

_Marco Morawec_
theFirehoseProject http://www.thefirehoseproject.com/
(808) 347-1135
